const dataReqDetails = [
    {
        writeAddress: '',
        officerName: '',
        selection: '',
        enNameThai: '',
        enNameEng: '',
        enCodeNumber: '',
        enLatitude: '',
        enLongitude: '',
        enX: '',
        enY: '',
        enNo: '',
        enMoo: '',
        enAlley: '',
        enSoi: '',
        enRoad: '',
        enProvince: '',
        enDistrict: '',
        enSubDistrict: '',
        enPostalCode: '',
        enPhone: '',
        enLimitedArea: '',
        enArea: '',
        enRoom: '',
        enBed: '',
        enOpenFirst: '',
        enCloseFirst: '',
        enOpenSecond: '',
        enCloseSecond: '',
    }
]