const dataReqInfo = [
   {
    pid : '1212121212121',
    namePersonal : 'นาย สมชาย',
    nameMiddlePersonal : '-',
    nameLastPersonal : 'ใจดี',
    birthDate : '01/01/2540',
    age : '30',
    sex : 'ชาย',
    nationality : 'ไทย',
    ethnicity : 'ไทย',
    religion : 'พุทธ',
    career : 'พนักงานบริษัท',
    income : '20,000',
    fatherName : 'นาย สมพ่อ ใจดี',
    motherName : 'นาง สมแม่ ใจดี',
    houseCode : '123456789',
    houseNumber : '123',
    moo : '1',
    alley : '-',
    soi : '-',
    street : 'สุขุมวิท',
    subDistrict : 'คลองเตย',
    district : 'คลองเตย',
    province : 'กรุงเทพมหานคร',
    postalCode : '10110',
    tel : '0123456789',
    fax : '0123456789',
    mobilePhone : '0123456789',
    placeIssue : 'สำนักทะเบียนคลองเตย',
    provinceIssue : 'กรุงเทพมหานคร',
    districtIssue : 'คลองเตย',
    legalType : 'ห้างหุ้นส่วนจำกัด',
    placeRegistration : 'คลองเตย',
    registrationNumber : '123456789',
    dateFounded : '01/01/2547',
    building : 'อาคาร 1',
    floor : '1',
    villageName : 'หมู่บ้าน 1',
    email : 'example@example.com',
   }
  ]
    
  export default dataReqInfo
  